@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}
@recipientId = e106842f-c863-4fae-bd6e-8816d8f4baff

# @name register_user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Arthur Rios",
  "email": "arthur2@acme.com",
  "cpf": "05011030103",
  "password": "123456",
  "role": "COURIER"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "cpf": "05011030156",
  "password": "123456"
}

###

# @name create_order
POST {{baseUrl}}/orders/{{recipientId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "New Order",
  "description": "A new order",
  "latitude": 0.0,
  "longitude": 0.0
}
