services:
  postgres:
    container_name: fast-feet-nest-clean-pg
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: fast-feet-nest-clean
      PG_DATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

  cache:
    container_name: fast-feet-nest-clean-redis
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data/redis